2025-08-06 15:11:12,525 - ETL - INFO - Source directory: /data/
2025-08-06 15:11:12,526 - ETL - INFO - Input files: ['ESFURN_data_collection.xlsx', 'diagnosis_codes.csv', 'drug_codes.csv', 'tissue_codes.csv', 'muc_therapy_other_therapies.csv']
2025-08-06 15:11:12,526 - ETL - INFO - Connecting to database...
2025-08-06 15:11:12,661 - ETL.Core - INFO - Git version: b5370f8
2025-08-06 15:11:12,661 - ETL.Core - INFO - Git tag: v1.6.2
2025-08-06 15:11:12,661 - ETL.Core - INFO - ESFURN Site: CNIO
2025-08-06 15:11:12,661 - ETL.Core.ValidateLookupFiles - INFO - ################################
2025-08-06 15:11:12,662 - ETL.Core.ValidateLookupFiles - INFO - ## Preprocess of lookup files ##
2025-08-06 15:11:12,662 - ETL.Core.ValidateLookupFiles - INFO - ################################
2025-08-06 15:11:12,662 - ETL.Core.ValidateLookupFiles - INFO - Inserting missing concepts from standard_concept_lookup.csv in concept table...
2025-08-06 15:11:12,765 - ETL.Core.ValidateLookupFiles - INFO - Concept 37153063 inserted!
2025-08-06 15:11:12,766 - ETL.Core.ValidateLookupFiles - INFO - Concept 37156145 inserted!
2025-08-06 15:11:12,767 - ETL.Core.ValidateLookupFiles - INFO - Validating concepts from drug_codes.csv ...
2025-08-06 15:11:12,777 - ETL - CRITICAL - Uncaught exception: Traceback (most recent call last):
  File "/etl/main.py", line 238, in main
    process.run_etl(
  File "/etl/etl/process.py", line 83, in run_etl
    preprocess_lookup_files.preprocess_lookup_files(
  File "/etl/transform/preprocess_lookup_files.py", line 154, in preprocess_lookup_files
    _preprocess_sites_lookup(session, source_directory, site_lookup_list)
  File "/etl/transform/preprocess_lookup_files.py", line 128, in _preprocess_sites_lookup
    _validate_concept_ids_in_csv(
  File "/etl/transform/preprocess_lookup_files.py", line 105, in _validate_concept_ids_in_csv
    df = pd.read_csv(data_path + filename, sep=";")
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/etl/csv/drug_codes.csv'

